// <auto-generated />
using System;
using HackneyBookingAPI.Models.BookingDataContextNS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HackneyBookingsAPI.Migrations
{
    [DbContext(typeof(BookingDataContext))]
    [Migration("20220330103651_InitialDatabase")]
    partial class InitialDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("HackneyBookingAPI.Models.BookingNS.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int?>("LocationNameId")
                        .HasColumnType("integer");

                    b.Property<bool>("PaymentReceived")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("LocationNameId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HackneyBookingAPI.Models.Location.LocationPlace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("HackneyBookingAPI.Models.BookingNS.Booking", b =>
                {
                    b.HasOne("HackneyBookingAPI.Models.Location.LocationPlace", "LocationName")
                        .WithMany()
                        .HasForeignKey("LocationNameId");

                    b.Navigation("LocationName");
                });
#pragma warning restore 612, 618
        }
    }
}
